name: RevivedLocyItem
main: com.locydragon.rli.RevivedLocyItem
version: 1.3.4
author: LocyDragon
depend: [PlaceholderAPI,ProtocolLib]
api-version: '1.20'
commands:
  rli:
  rlitem:
  revivedlocyitem: