name: RevivedLocyItem
main: com.locydragon.rli.RevivedLocyItem
version: 1.3.6
author: LocyDragon
depend: [PlaceholderAPI,ProtocolLib]
softdepend: [MythicMobs]
loadbefore: [Quests]
api-version: '1.13'
description: A solution for all things item-related.
commands:
  rli:
    description: Rli base command
  rlitem:
    description: Rli base command
  revivedlocyitem:
    description: Rli base command